[package]
name = "timely-rays"
version = "0.1.0"
authors = ["Thomas Parks <thomasparks@outlook.com>"]

[dependencies]
timely="*"
abomonation="*"
nalgebra = "0.13"
approx="*"
image = "*"
rand = "0.3"
itertools = "*"
